### ISSUE TITLE
workflow-wm-osx does not support multiple displays

### ISSUE THREAD

**Issue by relekang** [havardh/workflow#101]
When run with multiple displays this is the output:
```
SyntaxError: Unexpected token { in JSON at position 31
    at JSON.parse (<anonymous>)
    at Osx.screen (/Users/rolf/.workflow/node_modules/workflow-wm-osx/dist/index.js:46:36)
    at screen (/Users/rolf/.nvm/versions/node/v8.11.2/lib/node_modules/workflow/node_modules/workflow-core/dist/index.js:85:13)
    at Object.screen (/Users/rolf/.nvm/versions/node/v8.11.2/lib/node_modules/workflow/node_modules/workflow-core/dist/index.js:96:25)
    at exec$1 (/Users/rolf/.nvm/versions/node/v8.11.2/lib/node_modules/workflow/node_modules/workflow-cmd/dist/index.js:74:33)
    at <anonymous>
```

I also ran the same command that the package runs in exec:

```
$ system_profiler SPDisplaysDataType | grep Resolution | awk '{ printf "{\\"width\\": %s, \\"height\\": %s}", $2, $4 }'
awk: syntax error at source line 1
 context is
	{ printf >>>  "{\\"width\ <<< \": %s, \\"height\\": %s}", $2, $4 }
awk: illegal statement at source line 1
	extra }
```

The solution to #100 might affect this issue.

**Comment by havardh** [comment]
Support for multiple monitors are planned for `workflow`. This support will likely make the flow files able to specify which monitors the different applications should be placed on. 

Until this support is added, I propose we try to solve this bug in the following way: Open the flow on the "active" monitor. Where the active monitor is the monitor with the _active_ application which `workflow` is executed from.

**Comment by relekang** [comment]
Yeah, let's see what come of #100 since the current source of info don't give the information of the active screen. However, it says which screen is the main display.
```
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2880 x 1800 Retina
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
        Thunderbolt Display:
          Display Type: LCD
          Resolution: 2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
          UI Looks like: 2560 x 1440
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Display Serial Number: C02ND5EQF2GC
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
          Connection Type: DisplayPort
```

**Comment by havardh** [comment]
That could be a start in the mean time. So that it's not broken at least.
