### ISSUE TITLE
Does not work on macOS mojave (10.14)

### ISSUE THREAD

**Issue by relekang** [havardh/workflow#158]
This permission popup is shown the first time one program tries to control another program:
![screenshot 2018-09-18 09 33 03](https://user-images.githubusercontent.com/476364/45671593-11684e80-bb26-11e8-88e4-d823c6e49579.png)

Workflow does not wait for it to be clicked so it tries to interact with a window that does not exist, at least that is what I think the invalid index means. 

```
{ Error: Command failed: /usr/bin/osascript -l JavaScript
360:391: execution error: Error on line 14: Error: Invalid index. (-1719)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/osascript -l JavaScript' }
```

**Comment by havardh** [comment]
Is this similar to the general Accessibility permissions that `workflow` needs to work on older versions of osx, only more granular?

If so, is there a way of granting this permission on a permanent basis? That would at solve the problem, but be quite annoying, if we need to grant permissions for each app.

**Comment by relekang** [comment]
I find it in settings, but it only have apps that I have tried to open. It does not seem like there is a generic setting.

![screenshot 2018-09-18 09 49 06](https://user-images.githubusercontent.com/476364/45672360-3cec3880-bb28-11e8-89c8-e1cb160f7b42.png)
