### ISSUE TITLE
Installation fails under windows

### ISSUE THREAD

**Issue by havardh** [havardh/workflow#174]
## Steps to reproduce
 - install `window-build-tools` as described in the manual.
 - install workflow `npm i -g workflow` in PowerShell

(The actual steps included running `npm i -g create-workflow-home` and `npm i` in ~/.workflow) 

## Expected

Working installation of `workflow`

## Actual

```
Users\hakon.dissen\AppData\Roaming\nvm\v9.7.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(111): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(111): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(114): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(114): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(123): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(123): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(124): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(124): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(125): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(125): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\callback_info.cc(63): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(126): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan.h(1647): note: see declaration of 'Nan::Callback::Call'
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(126): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\callback_info.cc(73): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan.h(1647): note: see declaration of 'Nan::Callback::Call'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\callback_info.cc(78): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(132): error C2664: 'v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>,v8::Local<v8::Value>,v8::Local<v8::Value>,v8::PropertyAttribute)': cannot convert argument 3 from 'v8::PropertyAttribute' to 'v8
::Local<v8::Value>' [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan.h(1647): note: see declaration of 'Nan::Callback::Call'
  c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(132): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(58): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(59): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(60): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(63): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(64): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(65): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(78): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(88): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(91): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(94): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(97): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
c:\users\hakon.dissen\.workflow\node_modules\ffi\src\ffi.cc(367): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\hakon.dissen\.workflow\node_modules\ffi\build\ffi_bindings.vcxproj]
  c:\users\hakon.dissen\.workflow\node_modules\nan\nan.h(1647): note: see declaration of 'Nan::Callback::Call'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\hakon.dissen\AppData\Roaming\nvm\v9.7.1\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hakon.dissen\\AppData\\Roaming\\nvm\\v9.7.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\hakon.dissen\.workflow\node_modules\ffi
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN workflow-user-home@2.0.3 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hakon.dissen\AppData\Roaming\npm-cache\_logs\2018-09-25T12_44_35_428Z-debug.log
```

**Comment by havardh** [comment]
@haakondi Is this accurate to what we did? Could you add version info like `node`, `npm` etc?
